#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/ignu/vim-rubocop.git",
  "git://github.com/slim-template/vim-slim.git",
  "git://github.com/Lokaltog/vim-easymotion.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/jnwhiteh/vim-golang.git",
  "git://github.com/kien/ctrlp.vim.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/juvenn/mustache.vim.git",
  "git://github.com/tpope/vim-bundler.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/ecomba/vim-ruby-refactoring",
  "git://github.com/airblade/vim-gitgutter.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/airblade/vim-rooter.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-matchit.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/bogado/file-line.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/vitaly/vim-syntastic-coffee.git",

  #"git://github.com/tpope/vim-dispatch.git",
  # TMUX
  "git://github.com/LnL7/vim-tslime.git",
  "git://github.com/jgdavey/vim-turbux.git",

  #COLORS
  "git://github.com/junegunn/seoul256.vim.git",
  "git://github.com/w0ng/vim-hybrid.git",
  "git://github.com/nanotech/jellybeans.vim.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/noahfrederick/vim-hemisu.git"
]

vim_org_scripts = [
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

