-- "Forked" from https://github.com/LunarVim/Neovim-from-scratch as I wanted to start
-- clean, but also have a working vim. Also don't want to deal with submodules.

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.snippets")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.sessions")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.yanky")
